JSON_SORT_KEYS = false # don't sort keys in alphabetical order when sending JSON responses
SECRET_KEY = ""
JWT_SECRET_KEY = ""
MAIL_USE_TLS = true
MAIL_SERVER = ""
MAIL_DEFAULT_SENDER = ""
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
mongo_address = ""