from app import db, Question

ms = [Question(id=1,
               text1="Find the gaseous compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/XtX944c.gif",
               text2="",
               answers="sulfur dioxide;SO2"),
      Question(id=2,
               text1="Find the gaseous compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/3okdkqT.gif",
               text2="",
               answers="formaldehyde;methanal;CH2O;H2CO"),
      Question(id=3,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/M4o462D.gif",
               text2="",
               answers="2,3-butadione;buta-2,3-dione;CH3COCOCH3"),
      Question(id=4,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/SMrzZgJ.gif",
               text2="",
               answers="nitromethane;CH3NO2"),
      Question(id=5,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/3G9TqYP.gif",
               text2="",
               answers="pyridine;C5H5N"),
      Question(id=6,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/j1JXocr.gif",
               text2="",
               answers="propenoic acid;acrylic acid;CH2CHCOOH;CH2CHCO2H"),
      Question(id=7,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/mi2jVRT.gif",
               text2="",
               answers="bromoacetic acid;CH2BrCOOH;CH2BrCO2H"),
      Question(id=8,
               text1="Find the pure liquid compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/w1KE5uV.gif",
               text2="",
               answers="iodoethane;CH3CH2I"),
      Question(id=9,
               text1="Find the gaseous compound that would give this mass spectrum.",
               imgsrc="https://i.imgur.com/Lr0jzrz.png",
               text2="",
               answers="1-butene;2-butene;but-1-ene;but-2-ene;butene;CH2CHCH2CH3;CH3CHCHCH3")]

for i in ms: db.session.add(i)
db.session.commit()
