from app import db, MSQuestion

db.create_all()

questions = [
    MSQuestion(1,
               "Find the gaseous compound that would give that mass spectrum.",
               "https://i.imgur.com/XtX944c.gif",
               "",
               "The compound does not contain carbon or hydrogen.",
               "The compound is a common contributor to acid rain.",
               "sulfur dioxide;SO2"),
    MSQuestion(2,
               "Find the gaseous compound that would give that mass spectrum.",
               "https://i.imgur.com/3okdkqT.gif",
               "",
               "How many hydrogens are there in this compound?",
               "The compound is used to preserve tissues and organs.",
               "formaldehyde;methanal;CH2O"),
    MSQuestion(3,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/M4o462D.gif",
               "",
               "The compound is symmetrical about its centre.",
               "What do the peaks at m/z=15 and m/z=43 commonly represent?",
               "2,3-butadione;buta-2,3-dione;CH3COCOCH3"),
    MSQuestion(4,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/SMrzZgJ.gif",
               "",
               "m/z=30 and m/z=46 are signs of what functional group?",
               "The compound is used as a fuel additive in motor sports.",
               "nitromethane;CH3NO2"),
    MSQuestion(5,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/3G9TqYP.gif",
               "",
               "The compound is aromatic.",
               "What does the m/z of the molecular ion tell you about what atoms are present?",
               "pyridine;C5H5N"),
    MSQuestion(6,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/j1JXocr.gif",
               "",
               "The compound is soluble in water.",
               "Derivatives of this compound are used to create sturdy plastics.",
               "propenoic acid;acrylic acid;CH2CHCOOH;CH2=CHCOOH;CH2CHCO2H;CH2=CHCO2H"),
    MSQuestion(7,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/mi2jVRT.gif",
               "",
               "Consider the molecular ion peak and nearby peaks. What do they tell you?",
               "The compound contains a halogen.",
               "bromoacetic acid;BrCH2COOH;BrCH2CO2H;CH2BrCOOH;CH2BrCO2H"),
    MSQuestion(8,
               "Find the pure liquid compound that would give that mass spectrum.",
               "https://i.imgur.com/w1KE5uV.gif",
               "",
               "Why are there no peaks between 30 and 127?",
               "The compound does not contain oxygen or nitrogen.",
               "iodoethane;CH3CH2I"),
    MSQuestion(9,
               "Find the gaseous compound that would give that mass spectrum.",
               "https://i.imgur.com/Lr0jzrz.png",
               "",
               "The compound exists has 2 isomers, both of which are valid answers to this question.",
               "The compound does not contain oxygen or nitrogen.",
               "1-butene;but-1-ene;2-butene;but-2-ene;butene,CH3CHCH3;CH3CH=CHCH3;CH2CH2CH2CH3;CH2=CH2CH2CH3"),
]

for question in questions:
    db.session.add(question)

db.session.commit()