[tool.poetry]
name = "chemquest-mithril"
version = "0.1.3"
description = "An automatic question generator for organic chemistry."
authors = ["unriellistic"]
license = "MPL 2.0"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.2.2"
gunicorn = "^20.1.0"
pymongo = {extras = ["srv"], version = "^4.2.0"}

[tool.poetry.dev-dependencies]
pylint = "^2.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
